### ISSUE TITLE
cell_value(rowx,colx) returns rounded imprecise float values

### ISSUE THREAD

**Issue by ambodi** [python-excel/xlrd#135]
I have a float type cell in my excel sheet that its value is originally set to ```4,42334285714286```. Upon reading it with the following code, it becomes ```4,42334285714```:
```python
value = data_sheet.cell_value(rowx=rx, colx=colx)
```

Is there a way to receive data with full precision? This is becoming an issue for my case.

**Comment by sjmachin** [comment]
xlrd does NOT truncate or otherwise fiddle with float data. 

You don't say what makes you believe that xlrd is chopping 3 digits off your value, however I'm willing to bet that you are using python 2.7 and using "print" or "str" ... see below (Python 2.7):

>>> a = 4.42334285714286
>>> str(a)
'4.42334285714'
>>> repr(a)
'4.42334285714286'
>>> print(a)
4.42334285714

Remedy: don't use str() or a raw "print" when you need to see full precision in Python 2.x, or use Python 3.x.

**Comment by ambodi** [comment]
Yeah, I actually found the solution before this. Thanks for your help. It's a big misunderstanding in newbies in python.
