### ISSUE TITLE
Availability of Sheet.merged_cells

### ISSUE THREAD

**Issue by sjmachin** [python-excel/xlrd#137]
Currently:
xls file: only when formatting_info=True (otherwise an empty list)
xlsx file: only when formatting_info=False (using formatting_info=True causes an Exception)

Proposed change:
xls file: provide the list of merged cells unconditionally
xlsx file: no change

Comments please.

**Comment by cjw296** [comment]
Can we change the default for formatting_info to True?
We can do it as part of a 1.0 release, along with some other default changes.
I appreciate that people may want to turn formatting_info off, but it's the exception rather than the norm...

**Comment by sjmachin** [comment]
I'm 50-50 on this ... how about you publish this and your some other default changes here and in the Google group so that others can comment?

**Comment by jkyeung** [comment]
Don't know if I'm too late to the party, but I actually lean toward defaulting to False, *if formatting info is still unavailable for .xlsx files*. The reason is that I think it's nicer for xlrd to behave as similarly as possible for both .xls and .xlsx files. If formatting info is going to be available for .xlsx files in the 1.0 release, then I give a hearty +1 to defaulting to True.

**Comment by cjw296** [comment]
@sjmachin - I'm 👍 on the original change you suggested, please feel free to push a commit...
