### ISSUE TITLE
Need access to raw value

### ISSUE THREAD

**Issue by mkleehammer** [python-excel/xlrd#140]
I need access to the raw value for text fields that are all digits.

For example, I cannot tell the difference between "1234" and "1234.0" in text cells.  The xlsx file contains a cell with "1234" but no type, so xlrd uses the default 'n' and converts it to a float.  This happens regardless of the number format - General, Text, etc.

Adding a new field for the raw value seems like a great approach, but something I could also work with would be a flag to not convert anything - always pass back the raw value if the flag is set.

Any interest in either of these approaches?

**Comment by cjw296** [comment]
You are misunderstanding what's happening here, please ask about this on the mailing list.

(sort version, your xlsx has a float stored, whatever wrote it chose to do that, xlrd is already giving you the "raw" value you're asking for...)

**Comment by mkleehammer** [comment]
Actually I'm not misunderstanding it - I've written an XLSX parser also, but for Javascript.  The raw value in the XML is "1234" and the field is formatted as text.  There is no `t` attribute so the code defaults to a number format (`cell_type = cell_elem.get('t', 'n')`).  It then, without looking at the number format casts it to a float.

```xml
<c r="A2" s="1">
  <v>1234</v>
</c>
```

I don't see anything special in the styles in this case that would lead it to be treated as text or a number, but in any case the style isn't examined.

I also suspect, but have not tested yet, that a custom date format could also be incorrectly treated as a number instead of a date - they don't always have `t="d"`.  I had to loop through the styles and examine custom ones for the date formatting codes.  I would keep a list of those styles and look for type "d" *or* a style from that list.

Try it yourself - create a spreadsheet with 1 cell with the value "1234" and format it as text.  Then read it in with xlrd - it will return the float 1234.  The problem is the format could be important - what if has variable leading zeros like "00123" or if "1234" and "1234.0" are very different things - both of these are issues in my case.

An option to also expose the raw value seems like a useful feature.

**Comment by jkyeung** [comment]
OK, I tried it myself, using Excel. I made one cell with the value "001234", entering it with a leading apostrophe. I tried to enter 01234 into a cell without a leading apostrophe and of course Excel immediately treats that as the number 1234 (float 1234.0). I use the menus to select Text format for the second cell, save the workbook, and read it with xlrd.

The first cell has the value u'001234', as expected. The second cell is as you describe, still numeric.

Now here's the interesting thing: again using Excel, I went back into the second cell to edit it, giving it a leading zero, which it can now accept because it is now formatted as Text. When I save that, xlrd reads the value as u'01234' and the cell type as text! Further, when I edit it again and delete the leading zero, saving it, the new value is u'1234', with type text.

So, Excel seems to have the peculiar property that if you *enter* a number, it *stays* a number, regardless of formatting, unless you edit it. Once edited, "text-formatted numbers" seem to stay text.

Which means the leading-zero thing is not so much an issue, because if someone enters something as text, with leading zeros, Excel is going to save it as such. Unfortunately, if xlrd reports the value 1234.0, then even if you know it was supposed to be text, you can't tell if what was actually keyed in was `1234`, `1234.0`, or `1234.00`, because they will all just show up as `<v>1234</v>`.

For completeness, I'll mention that if you entered 1234 and used custom numeric format '00000' to create a leading zero, Excel will display `01234` in the cell, but still show `1234` in the formula bar and in the `v` tag of the cell in the saved file.

All of which means that even if you *could* get what you're calling the "raw value", this still doesn't tell you what you are trying to find out. Thus the feature is not as useful as you've made it out to be.

I think it would be more useful to get the actual format string.

**Comment by mkleehammer** [comment]
First, there is no format string and the number type is '0'.  Check your example.

Second, it is useful if you know what type to expect in each cell or column, which I do.  Lots of programs use Excel for ETL and import jobs.  For example, I may know the "partno" column is always text, so all I want is the raw value for that column - it is already correct.

**Comment by jkyeung** [comment]
<blockquote>First, there is no format string and the number type is '0'. Check your example.</blockquote>
Which example are you referring to? I'm quite sure I gave several. In the absence of any other information, what you're describing is exactly what I would expect for cell format `General`.

<blockquote>I may know the "partno" column is always text, so all I want is the raw value for that column - it is already correct.</blockquote>
I don't think you really absorbed what I was trying to say. Let's suppose you are inspecting a .xlsx file in which a user has entered what looks to them like `1234.00` in the "partno" column. Their part number is one-two-three-four-dot-zero-zero. But they didn't know the proper way to coerce Excel to treat it as text; they used two decimal places of formatting instead. You know it's supposed to be text; *they* know it's supposed to be text. But they got the "correct" value to show up the way they know how. They may even be proud of themselves for "fixing" the problem of preserving the trailing characters.

Now, when you read this part number, xlrd will tell you it's 1234.0 (the float, which is exactly what Excel has stored in the file); if you're parsing the XML by other means, you will encounter `<v>1234</v>`. That is, it has a "raw value" of `1234`.

How will you extract the proper part number (`1234.00`) without the format string?

You may say "that would never happen". If the file in question contains manually entered data or is otherwise subject to human intervention before it gets to you, I would beg to differ. But let's suppose you're right and it would never happen. So then why not just use your knowledge that the part number is text to fix it yourself? Depending on your knowledge of the possible values for the part number, it might be appropriate to use logic along the lines of

    cell = ws.cell(rx, cx)
    if cell.ctype == xlrd.XL_CELL_TEXT:
        partno = cell.value
    elif cell.value == int(cell.value):
        partno = str(int(cell.value))
    else:
        partno = str(cell.value)

Or perhaps

    cell = ws.cell(rx, cx)
    if cell.ctype == xlrd.XL_CELL_TEXT:
        partno = cell.value
    else:
        partno = str(cell.value)
        if partno.endswith('.0'):
            partno = partno[:-2]

To me, this approach is at least as robust as using the contents of the `v` tag.
