### ISSUE TITLE
xlrd can't suppress OLE2 inconsistency warning

### ISSUE THREAD

**Issue by willdzeng** [python-excel/xlrd#187]
Notice:
https://github.com/python-excel/xlrd/blob/master/xlrd/compdoc.py#L261

the warning is printed, so we can't suppress the warning even if everything is fine.
Maybe change all the warning prints by using warning library?
so that we can suppress by
https://docs.python.org/2/library/warnings.html#temporarily-suppressing-warnings

**Comment by gsauthof** [comment]
It's true that printing warnings to stdout, by default instead of using the standard Python logging package is a bit annoying.

You can work around this via supplying the optional `logfile` argument when calling xlrd functions like `open_workbook`. For example, to redirect xlrd warnings to stderr:

    w = xlrd.open_workbook(filename, logfile=sys.stderr)

Or, to suppress all xlrd logging:

    w = xlrd.open_workbook(filename, logfile=open(os.devnull, 'w'))

Alternatively, you can use a no-op file-like object ([see also](https://bugs.python.org/issue28864)):

    class NullWriter:
        def write(self, s):
            pass
            # etc.
      
    w = xlrd.open_workbook(filename, logfile=NullWriter())

Perhaps the project owner would even except a pull request that replaces the current print-style logging with Python `logging` calls.

**Comment by cjw296** [comment]
Yes, I think a PR for this would be accepted.

**Comment by gsauthof** [comment]
Regarding XLS vs. XLSX: there seem to exist legacy appliances that write records into xls files ... And customers who don't want to change anything are happy to pay a vendor money for supporting xls as input format.

**Comment by cjw296** [comment]
Heh, if anyone would like to pay for the ongoing maintenance burden of xlrd, that would be welcome!

**Comment by cjw296** [comment]
PR has been merged.
