### ISSUE TITLE
AreaN error

### ISSUE THREAD

**Issue by SheetJSDev** [python-excel/xlrd#70]
```
xlrd.formula.FormulaError: ERROR *** Token 0x2d (AreaN) found in NAME formula
```

**Comment by dannguyen** [comment]
Sorry to bump this, but getting this exact error with these census files:

http://www.nyc.gov/html/dcp/html/census/socio_tables.shtml

Specifically these Household income files:

http://www.nyc.gov/html/dcp/download/census/sf3incp1si.xls

In Excel 2011 (OSX), this is the error that pops up:

![image](https://cloud.githubusercontent.com/assets/121520/11401697/6e9d0fa2-9359-11e5-9a88-72b49b3285c4.png)

However, after saving the file (after Excel has made the ad-hoc correction), `open_workbook` works just fine.

So being able to have an option to ignore this warning and fill the errant field with some NULL or N/A value would be sufficient, since it seems that is what Excel itself does.

**Comment by cjw296** [comment]
I'd suggest reporting it to nyc.gov and getting them to fix their broken files...

**Comment by dannguyen** [comment]
@cjw296 Oh getting around this specific problem is easy enough, I'm just providing an example as requested about how Excel handles such errors. Having a way to ignore this error will be of much greater use to more users going forward, especially those who need to do bulk processing of such files.

I think this kind of error is not completely uncommon or unique to governmental agencies. And the naive way that Excel seems to get past it seems to be a good enough solution.

**Comment by cjw296** [comment]
Well, being realistic, this isn't going to get fixed unless there's a pull request, so closing for now.
If you have the problem, please report by way of a pull request that includes tests demonstrating the problem.
